name: Auto-assign past contributors as reviewers

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install GitHub CLI
      - name: Setup GitHub CLI
        uses: actions4gh/setup-gh@v1.0.2

      # Specify the paths to include (space-separated, e.g. "src/ lib/")
      - name: Set included paths
        run: echo "INCLUDE_PATHS=app/ test/" >> $GITHUB_ENV

      - name: Get changed files (filtered by included paths)
        id: files
        run: |
          ALL_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          FILTERED_FILES=""
          for FILE in $ALL_FILES; do
            for PATH in $INCLUDE_PATHS; do
              if [[ "$FILE" == "$PATH"* ]]; then
                FILTERED_FILES="${FILTERED_FILES}${FILE}"$'\n'  
                break
              fi
            done
          done
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$FILTERED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Find reviewers (Bash)
        id: reviewers
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR=${{ github.actor }}

          REVIEWERS=""

          while IFS= read -r FILE_PATH; do
            [ -z "$FILE_PATH" ] && continue

            echo "Checking file: $FILE_PATH"
            resp=$(curl -s -H "Authorization: Bearer $TOKEN" \
              "https://api.github.com/repos/$OWNER/$REPO/commits?path=$FILE_PATH&per_page=1")

            login=$(echo "$resp" | jq -r '.[0].author.login // empty')
            name=$(echo "$resp" | jq -r '.[0].commit.author.name // empty')
            email=$(echo "$resp" | jq -r '.[0].commit.author.email // empty')
            sha=$(echo "$resp" | jq -r '.[0].sha // empty')

            echo "→ sha=$sha, login=$login, name=$name, email=$email"

            if [ -z "$login" ] || [ "$login" = "null" ]; then
              echo "❌ No GitHub username found for $FILE_PATH (email=$email)."
              exit 1
            fi

            # Skip PR author
            if [ "$login" != "$PR_AUTHOR" ]; then
              REVIEWERS="$REVIEWERS $login"
            fi
          done <<< "${{ env.FILES }}"

          # Deduplicate reviewers
          REVIEWERS=$(echo $REVIEWERS | xargs -n1 | sort -u | xargs)

          if [ -z "$REVIEWERS" ]; then
            echo "ℹ️ No additional reviewers found (PR author is the only/most recent contributor to all files). Skipping reviewer assignment."
            echo "REVIEWERS=" >> $GITHUB_ENV
          else
            echo "✅ Found reviewers: $REVIEWERS"
            echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
          fi

          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV

      - name: Assign reviewers to PR
        if: env.REVIEWERS != ''
        run: |
          echo "Adding reviewers: $REVIEWERS"
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer $REVIEWERS
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
